### ISSUE TITLE
How to use ValidatorBetween with a ValidatorChain?

### ISSUE THREAD

**Issue by jpaas** [dtop/SwiftValidate#11]
I'm having trouble doing the following:

``` swift
    let validatorChain = ValidatorChain() {
      $0.stopOnFirstError = true
      $0.stopOnException = true
      } <~~ ValidatorBetween<Int>() {
        $0.minValue = 1
       $0.maxValue = 10
    }
```

It says that `ValidatorBetween<Int>` does not conform to ValidationAwareProtocol

**Comment by dtop** [comment]
I will have a look into that and come back with a solution or a new release ;-)... thank you @jpaas

**Comment by dtop** [comment]
Hi @jpaas ,

there was a protocol missing in several validators.
the 0.0.9 release solves this.

Thank you for contributing to the quality by reporting!

Best,
D.
