### ISSUE TITLE
swift 3 compatibility

### ISSUE THREAD

**Issue by felipecarreramo** [dtop/SwiftValidate#19]
do you have an approximate date to include swift 3 compatibility?

**Comment by RafaelGali** [comment]
> do you have an approximate date to include swift 3 compatibility?

@dtop I also need it urgently, please. The branch **beta/swift3** doesn't work.

**Comment by dtop** [comment]
sorry guys I was on vacation ;-) ... will do it over the weekend

**Comment by dtop** [comment]
Hey!

it was less to do than expected.
I've updated the beta/swift3 branch and draft a new beta release.

Best,
D.

**Comment by RafaelGali** [comment]
> Hey!
> 
> it was less to do than expected.
> I've updated the beta/swift3 branch and draft a new beta release.
> 
> Best,
> D.

Thank you very much @dtop ;)
