### ISSUE TITLE
feature request: example project, ideally using Eureka

### ISSUE THREAD

**Issue by jpaas** [dtop/SwiftValidate#4]
@dtop this pod looks really interesting, but I'm finding it a little slow to get going. I'd like to get it working with Eureka. A Eureka example project would be great. Ideally that demonstrates things like:
- multiple form rows, each with their own validations
- enabling/disabling a submit button based on whether the form is valid
- displaying validation errors on the corresponding form rows

In the meantime, I'll keep muddling along. 

FYI - there's something about your podspec that makes your pod unable to be "expanded" in the cocoapods search results. Try searching on "valid" for swift projects and you'll see what I mean. Yours is the only one in the list that can't be expanded and viewed inline.

**Comment by dtop** [comment]
@jpaas yes, the example project will come during next weeks.

unfortunately is eureka not able to display errors in cells so maybe you have to show the error messages in some AlertView or something.

I will figure out something in the example project.

thanx for the information with the podspec I'll fix this if I can 

_Edit:_ for some reason the old podspec (search for "swift validate") is expandable but the new one
is not

**Comment by dtop** [comment]
https://github.com/dtop/swift-validate-example 

its not very much but still an example ;-)
