### ISSUE TITLE
Several issues with ValidatorEmail

### ISSUE THREAD

**Issue by jpaas** [dtop/SwiftValidate#7]
1. splitEmailAddress will crash if the results of splitting the string based on @ only returns 1 part. e.g. If the input is `a@` this returns a partial array of length 1, but the returned tuple assumes it is at least 2.
2. There doesn't appear to be a check that the domain has a tld. An input of `a@b` is returned as valid.
3. There doesn't appear to be a check that the tld is at least 2 characters. An input of `a@b.c` is returned as valid.

**Comment by jpaas** [comment]
A nice workaround for now:

``` swift
        <~~ ValidatorRegex() {
          $0.errorMessageValueIsNotMatching = "Invalid email"
          $0.options = [.CaseInsensitive]
          $0.pattern = "\\A\\s*([^@\\s]{1,64})@((?:[-\\p{L}\\d]+\\.)+\\p{L}{2,})\\s*\\z"
        }
```

**Comment by dtop** [comment]
Thanks for reporting!

I did a fix in RC7 branch that allows TLD validation.
a@b is also valid (consider root@localhost) so the old check is optional but enabled by default.

the crash is also solved, sorry for that.
there will be a new version within the next days

**Comment by jpaas** [comment]
Thanks @dtop. So far the pod has been working quite nicely for me. FYI - I posted an example of how I am using it on the Eureka issue that is discussing validation... https://github.com/xmartlabs/Eureka/issues/47
